### ISSUE TITLE
Backport S-DD1 emulation.

### ISSUE THREAD

**Issue by orbea** [libretro/snes9x2002#17]
This will fix rendering graphics in such games as Star Ocean. This was fixed in snes9x2005 in commit https://github.com/libretro/snes9x2005/commit/1f2818bdd38cc225faa840e1aca100866e515046.

Example of the title screen:
![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/snes9x2002/Star%20Ocean%20%28Japan%29%20%5bEn%20by%20DeJap%20v1.0%5d-160925-131702.png)

**Comment by aberusugi** [comment]
Still an issue today. Seeing as Retroflag's GPi case has increased use of Snes9x-2002 as a core, either the lakka team needs to drop snes9x-2002 (as this project seems dead based on this github activity) for slight performance drops otherwise, or someone needs to pickup expanding coprocessor support to 2002. I think the latter is not likely.
![IMG_20200429_121047](https://user-images.githubusercontent.com/16388068/80631622-3c5d9880-8a13-11ea-9335-9e1a20fa1c39.jpg)
